# Generated by Django 4.0.1 on 2023-03-14 17:01

from django.db import migrations, models
import django.db.models.deletion
import doorlockdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRuleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('token', models.CharField(default=doorlockdb.models.random_token, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLockKeys',
            fields=[
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doorlockdb.lock')),
                ('config_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('keys_json', models.TextField(default='[]')),
                ('synchronized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('access_groups', models.ManyToManyField(blank=True, to='doorlockdb.AccessGroup')),
                ('persons', models.ManyToManyField(blank=True, to='doorlockdb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwid', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='Enter a meaning full description. example="NS OV chipkaart t.h.t. 02-2027"', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorlockdb.person')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.DateTimeField(blank=True, default=None, null=True)),
                ('before', models.DateTimeField(blank=True, default=None, null=True)),
                ('weekdays_monday', models.BooleanField(default=True)),
                ('weekdays_tuesday', models.BooleanField(default=True)),
                ('weekdays_wednesday', models.BooleanField(default=True)),
                ('weekdays_thursday', models.BooleanField(default=True)),
                ('weekdays_friday', models.BooleanField(default=True)),
                ('weekdays_saturday', models.BooleanField(default=True)),
                ('weekdays_sunday', models.BooleanField(default=True)),
                ('time_start', models.TimeField(blank=True, default=None, null=True)),
                ('time_end', models.TimeField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='doorlockdb.accessrule')),
            ],
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='locks',
            field=models.ManyToManyField(blank=True, to='doorlockdb.Lock'),
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorlockdb.accessruleset'),
        ),
        migrations.CreateModel(
            name='LogUnknownKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwid', models.CharField(max_length=32, unique=True)),
                ('counter', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('lock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doorlockdb.lock')),
            ],
            options={
                'unique_together': {('hwid', 'lock')},
            },
        ),
        migrations.CreateModel(
            name='LogKeyLastSeen',
            fields=[
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doorlockdb.key')),
                ('counter', models.SmallIntegerField(default=0)),
                ('last_seen_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_seen_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('lock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doorlockdb.lock')),
            ],
        ),
    ]
