# Generated by Django 4.0.1 on 2023-03-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorlockdb', '0004_remove_accessrule_rules_accessrule_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrule',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorlockdb.accessruleset'),
        ),
    ]
