# Generated by Django 4.0.1 on 2023-05-23 14:52

from django.db import migrations, models
import doorlockdb.models



class Migration(migrations.Migration):

    dependencies = [
        ('doorlockdb', '0008_alter_key_description_alter_lock_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='token',
            field=models.CharField(default=doorlockdb.models.random_token, max_length=2000, unique=True),
        ),
    ]
