# Generated by Django 4.0.1 on 2023-05-30 11:02

from django.db import migrations, models
import doorlockdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('doorlockdb', '0009_alter_lock_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='certificate',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='lock',
            name='token',
            field=models.CharField(default=doorlockdb.models.random_token, max_length=200, unique=True),
        ),
    ]
