# Generated by Django 4.0.1 on 2023-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0005_alter_accessrule_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persongroup",
            name="persons",
        ),
        migrations.AddField(
            model_name="person",
            name="personsgroup",
            field=models.ManyToManyField(blank=True, to="doorlockdb.PersonGroup"),
        ),
        migrations.AlterField(
            model_name="synclockkeys",
            name="keys_json",
            field=models.TextField(default="{}"),
        ),
    ]
