# Generated by Django 4.0.1 on 2023-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0007_synclockkeys_last_log_keys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="key",
            name="description",
            field=models.CharField(
                help_text='Enter a meaning full description. example="NS OV chipkaart t.h.t. 02-2027"',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="lock",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disable access for all keys on this lock. This lock is still able to synchronize with the token.",
            ),
        ),
    ]
