# Generated by Django 4.0.1 on 2023-05-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0012_lockcertificate_fingerprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lockcertificate",
            name="fingerprint",
        ),
    ]
